# Generated by Django 2.1.4 on 2018-12-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=100)),
                ('leader', models.DecimalField(decimal_places=0, max_digits=1)),
                ('contract', models.CharField(max_length=2)),
                ('N', models.CharField(max_length=38)),
                ('E', models.CharField(max_length=38)),
                ('W', models.CharField(max_length=38)),
                ('S', models.CharField(max_length=38)),
                ('NS', models.BooleanField()),
                ('EW', models.BooleanField()),
                ('NS_Trick', models.DecimalField(decimal_places=0, max_digits=1)),
                ('EW_Trick', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('NS_TotalPoint', models.DecimalField(decimal_places=0, max_digits=5)),
                ('EW_TotalPoint', models.DecimalField(decimal_places=0, max_digits=5)),
                ('RoundNum', models.DecimalField(decimal_places=0, max_digits=2)),
                ('MachineID', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='TableID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.table'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.table'),
        ),
    ]
