# Generated by Django 2.1.4 on 2018-12-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='PlayerID',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
