# Generated by Django 2.1.4 on 2019-01-01 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0002_seat_playerid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('PlayerID', 'TableID'), ('position', 'TableID')},
        ),
    ]
