# Generated by Django 2.1.4 on 2019-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_auto_20190101_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounds',
            old_name='EW_Trick',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='EW',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='NS',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='NS_Trick',
        ),
        migrations.AddField(
            model_name='rounds',
            name='Rnum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rounds',
            name='declarer',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rounds',
            name='score',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rounds',
            name='vulnerable',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
