# Generated by Django 2.1.4 on 2019-01-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_auto_20190103_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='leader',
            field=models.CharField(max_length=1),
        ),
    ]
