# Generated by Django 2.1.4 on 2019-01-04 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_auto_20190104_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='HistoryGame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.rounds'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='PlayerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
