# Generated by Django 2.1.4 on 2019-01-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_auto_20190104_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='Event',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='Site',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='Rnum',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='T_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.table'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='bid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='declarer',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='vulnerable',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
