# Generated by Django 2.1.4 on 2019-01-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0009_auto_20190105_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='score',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
