# Generated by Django 2.1.4 on 2019-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0010_auto_20190105_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='result',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
