# Generated by Django 2.0.5 on 2019-01-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0011_auto_20190105_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dds_result',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='MachineID',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='RoundNum',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
