# Generated by Django 2.0.5 on 2019-01-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0012_auto_20190112_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='HistoryGame',
        ),
        migrations.AddField(
            model_name='rounds',
            name='E_play',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='N_play',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='S_play',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='W_play',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
