# Generated by Django 2.0.5 on 2019-01-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0013_auto_20190112_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dds_result',
        ),
        migrations.AddField(
            model_name='rounds',
            name='dds_result',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
