# Generated by Django 2.0.5 on 2019-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0015_table_dds_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dds_result',
        ),
        migrations.AlterField(
            model_name='rounds',
            name='contract',
            field=models.CharField(max_length=5),
        ),
    ]
